// <auto-generated />
namespace Football.Web.Data.Entities.Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Club : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Club));
        
        string IMigrationMetadata.Id
        {
            get { return "201803191637483_Club"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
